#include"trie.h"
#include"reader.h"
//#include"../hashtable/htbl.h"

static unsigned long ul_char_count = 0;


static trie_node *new_trie_node(unsigned int order);
static bool isStrPresent(trie *t, char *str);

trie* createTrie(unsigned int order, char key)
{
   trie *t = NULL;
   t = (trie*)calloc(1,sizeof(trie));
   if(t)
   {
      t->order = (order > ORDER_LIMIT) ? ORDER_LIMIT:order;
      t->ul_node_count = 0;
      t->addString = addString;
      t->isStringPresent = isStrPresent;
      t->unInit = freeT;
      t->head = new_trie_node(t->order);
      if(t->head)
      {
         t->head->data = key;
      }
      else
      {
         free(t);
         t = NULL;
      }
   }
   return (t);
}

trie_node *new_trie_node(unsigned int order)
{
   trie_node *node = NULL;
   node = (trie_node*)calloc(1, sizeof(trie_node));
   if(node)
   {
      node->link = (trie_node**)calloc(order, sizeof(trie_node*));
   }
   return (node);
}

void addNode(trie_node **head, char data)
{
   if(!(*head))
   {
      *head = new_trie_node(TRIE_DATA_TYPE_STRING);
      (*head)->data = data;
      printf("Added %c\n", (*head)->data);
   }
   else
   {
      printf("%c->", (*head)->data);
      addNode(&((*head)->link[GET_INDEX(data)]), data);
   }
}

void addString(trie *t, char *str)
{
   if(!str || !t)
      return;
   if(!t->head)
      return;

   /* Check if this is the right trie to add to */
   if(t->head->data != str[0])
      return;

   /* First char is trie head, skip it */
   str++;
   int len = strlen(str) + 1;
   ul_char_count += len + 1;
      
   trie_node *add = t->head;

   do
   {
      /* If link is NULL, add a new one and assign it data.
       * If link already present, don't add a node and just skip to 
       * next char to be added and the following node. */
      if(!(add->link[GET_INDEX(*str)]))
      {
//         printf("(new) %c", *str);
         add->link[GET_INDEX(*str)] = new_trie_node(t->order);
         if(add->link[GET_INDEX(*str)])
         {
            t->ul_node_count++;
            add->link[GET_INDEX(*str)]->data = *str;
         }
      }
      else
      {
//         printf("(old) %c", *str);
      }
//      printf("->");
      /* Increment str and get next node */
      add = add->link[GET_INDEX(*str)];
      str++;
   }while(--len);
//   printf("\n");
}


void freeTrie(trie *t, trie_node **head)
{
   int i = 0;
   if(!(*head) || !t)
      return;
   for(i = 0; i < t->order; i++)
   {
      if((*head)->link[i])
      {
         //printf("link %d on trie %c is valid\n", i, (*head)->data);
         freeTrie(t, &((*head)->link[i]));
         t->ul_node_count--;
      }
   }
   //printf("freeing %c\n", (*head)->data);
   free(*head);
   *head = NULL;
}
void freeT(trie *t)
{
   if(!t)
      return;
   printf("Free'ing trie with %ld nodes\n", t->ul_node_count);
   freeTrie(t, &(t->head));
   if(t->ul_node_count)
      printf("Memory leak! Failed to free %lu nodes\n", t->ul_node_count);
   free(t);
   t = NULL;
}

void freeAllTries(trie_node **head)
{
   int j = 0;
   /* Free all nodes from all trees */
   for(j = 0; j < 27; j++)
   {
      if(head[j])
      {
         freeTrie(NULL, &head[j]);
      }
   }
}

bool isStrPresent(trie *t, char *str)
{
   if(!t || !str)
      return;
   int len = strlen(str) + 1;
   
   trie_node *head = t->head;
   do
   {
      //printf("head->data: %c str: %c\n", head->data, *str);
      if(head->data != *str)
         break;
      str++;
      head = head->link[GET_INDEX(*str)];
      len--;
   }while(len && head);
   if(!len)
      return TRUE;
   return FALSE;
}
#if 0
bool isSubString(trie_node *head, char *string)
{
   if(!head || !string)
      return;
   while(*string && head)
   {
      if(head->data == (char)*string)
      {
         string++;
         head = head->link[GET_INDEX(*string)];
      }
   }
   if(!*string)
      return TRUE;
   return FALSE;
}
#endif
int main()
{
   /* Replace this with a hash table */
   trie **table = NULL;
   /* Reader to read tokens */
   reader *dict_rdr = NULL;
   /* Reader to read words generated by module */
   reader *word_rdr = NULL;
   int i = 0;
   char buffer[26];
   dict_rdr = newReader("dictionary.txt");
   if(!dict_rdr)
      goto LBL_EXIT;

   /* Create temp local hash-table */
   table = (trie**) calloc(26, sizeof(trie*));

   while(1)
   {
      dict_rdr->getNextToken(dict_rdr, buffer);
      if(buffer[0] == '\0')
      {
         printf("No more strings\n");
         break;
      }
      printf("Got %s\n", buffer);
      if(!table[GET_INDEX(buffer[0])])
      {
         table[GET_INDEX(buffer[0])] = createTrie(TRIE_DATA_TYPE_STRING, buffer[0]);
         printf("Created tree rooted at '%c'\n", table[GET_INDEX(buffer[0])]->head->data);
      }
         
      table[GET_INDEX(buffer[0])]->addString(table[GET_INDEX(buffer[0])], buffer);
      memset(buffer, 0, sizeof(buffer));
   }
   for(i = 0; i <26; i++)
   {
      if(table[i])
         printf("Table '%c' has %ld nodes\n", table[i]->head->data, table[i]->ul_node_count);
   }

#if 0
   /* Open words file to cross-reference against our dictionary trie */
   word_rdr = newReader("dictionary.txt");
   if(!word_rdr)
      goto LBL_EXIT;

   char buf[26];
   while(1)
   {
      word_rdr->getNextToken(word_rdr, buf);
      if(buf[0] == '\0')
      {
         printf("No more strings\n");
         break;
      }
      if(table[GET_INDEX(buf[0])]->isStringPresent(table[GET_INDEX(buf[0])], buf))
         printf("Valid word: %s\n", buf);
      memset(buf, 0, sizeof(buf));
   }
#endif   
   int d = 0;
   while(1)
   {
      scanf("%d", &d);
      if(d)
         break;
   }
LBL_EXIT:
   //freeAllTries(head);
   for(i = 0; i <26; i++)
   {
      if(table[i])
         table[i]->unInit(table[i]);
   }
   /* Close reader as we are done reading tokens */
   if(dict_rdr)
   {
      dict_rdr->unInit(dict_rdr);
      dict_rdr = NULL;   
   }
   if(word_rdr)
   {
      word_rdr->unInit(word_rdr);
      word_rdr = NULL;
   }
   free(table);
}
